name: CI

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'main' && 'prod' || inputs.environment }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install poetry

      - name: Install project
        run: poetry install --no-interaction --with dev

      - name: Run tests
        run: poetry run pytest

      - name: Run Ruff
        run: |
          poetry run ruff check .
          poetry run ruff format --check .