name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging, dev ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'LICENSE'
      - 'docs/**'
  pull_request:
    branches: [ main, staging, dev ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'LICENSE'
      - 'docs/**'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      environment: ${{ github.ref_name }}

  cd:
    needs: ci
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/cd.yml
    with:
      environment: ${{ github.ref_name }}
    secrets: inherit
